import os
import json


class ProjectScaffolder:
    def scaffold(self, boilerplate: dict, output_dir: str) -> dict:
        os.makedirs(output_dir, exist_ok=True)
        created_files   = []
        created_folders = []

        # Folders banao
        for folder in boilerplate.get("folder_structure", []):
            path = os.path.join(output_dir, folder.get("path", ""))
            os.makedirs(path, exist_ok=True)
            created_folders.append(path)

        # Key files banao
        for file in boilerplate.get("key_files", []):
            path    = os.path.join(output_dir, file.get("path", ""))
            content = file.get("content_snippet", "")
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            created_files.append(path)

        # requirements.txt banao
        deps = boilerplate.get("dependencies", [])
        if deps:
            req_path = os.path.join(output_dir, "requirements.txt")
            with open(req_path, "w", encoding="utf-8") as f:
                for dep in deps:
                    pkg     = dep.get("package", "")
                    version = dep.get("version", "")
                    purpose = dep.get("purpose", "")
                    f.write(f"{pkg}=={version}  # {purpose}\n")
            created_files.append(req_path)

        # .env.example banao
        env_vars = boilerplate.get("env_variables", [])
        if env_vars:
            env_path = os.path.join(output_dir, ".env.example")
            with open(env_path, "w", encoding="utf-8") as f:
                for var in env_vars:
                    key      = var.get("key", "")
                    example  = var.get("example", "")
                    required = var.get("required", False)
                    f.write(f"{'# Required' if required else '# Optional'}\n")
                    f.write(f"{key}={example}\n\n")
            created_files.append(env_path)

        # README banao
        readme_path = os.path.join(output_dir, "README.md")
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(self._build_readme(boilerplate))
        created_files.append(readme_path)

        return {
            "output_dir":      output_dir,
            "created_folders": len(created_folders),
            "created_files":   len(created_files),
            "files":           created_files
        }

    def _build_readme(self, boilerplate: dict) -> str:
        name     = boilerplate.get("project_name", "my_project")
        stack    = boilerplate.get("stack", {})
        steps    = boilerplate.get("quick_start", [])

        readme = f"# {name}\n\n"
        readme += f"**Stack:** {stack.get('framework', '')} | {stack.get('database', '')} | {stack.get('language', '')}\n\n"
        readme += "## Quick Start\n\n"
        for step in steps:
            readme += f"{step.get('step', '')}. {step.get('command', '')} — {step.get('description', '')}\n"
        readme += "\n> Generated by APIForge\n"
        return readme
