import os


class HTMLExporter:
    def export(self, report_data: dict, output_path: str) -> str:
        html = self._build_html(report_data)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        return output_path

    def _build_html(self, data: dict) -> str:
        meta    = data.get("meta", {})
        summary = data.get("summary", {})
        evidence = data.get("evidence", [])

        pass_rate = summary.get("pass_rate", 0)
        color     = "#22c55e" if pass_rate >= 80 else "#ef4444"

        rows = ""
        for e in evidence:
            status  = e["assertions"]["status"]
            bg      = "#f0fdf4" if status == "passed" else "#fef2f2"
            icon    = "✅" if status == "passed" else "❌"
            rows += f"""
            <tr style="background:{bg}">
                <td>{e.get('id','')}</td>
                <td><b>{e['endpoint']['method']}</b></td>
                <td style="font-size:12px">{e['endpoint']['url']}</td>
                <td>{e['response']['status_code']}</td>
                <td>{e['response']['latency_ms']}ms</td>
                <td>{icon} {status.upper()}</td>
                <td>{e['assertions']['passed']}/{e['assertions']['passed'] + e['assertions']['failed']}</td>
            </tr>"""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>APIForge Report — {meta.get('api_title','')}</title>
    <style>
        body {{ font-family: -apple-system, sans-serif; margin: 0; background: #f8fafc; color: #1e293b; }}
        .header {{ background: #0f172a; color: white; padding: 32px 48px; }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .header p {{ margin: 4px 0 0; opacity: 0.6; font-size: 14px; }}
        .container {{ padding: 32px 48px; }}
        .cards {{ display: flex; gap: 16px; margin-bottom: 32px; flex-wrap: wrap; }}
        .card {{ background: white; border-radius: 12px; padding: 20px 28px; min-width: 140px;
                 box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
        .card .val {{ font-size: 32px; font-weight: 700; }}
        .card .lbl {{ font-size: 13px; color: #64748b; margin-top: 4px; }}
        table {{ width: 100%; border-collapse: collapse; background: white;
                 border-radius: 12px; overflow: hidden;
                 box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
        th {{ background: #0f172a; color: white; padding: 12px 16px;
              text-align: left; font-size: 13px; }}
        td {{ padding: 12px 16px; font-size: 13px; border-bottom: 1px solid #f1f5f9; }}
        .badge {{ display: inline-block; padding: 2px 10px; border-radius: 99px;
                  font-size: 12px; font-weight: 600; }}
        .footer {{ text-align: center; padding: 24px; color: #94a3b8; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🔬 APIForge Test Report</h1>
        <p>{meta.get('api_title','')} v{meta.get('api_version','')} &nbsp;|&nbsp; {meta.get('generated_at','')}</p>
    </div>
    <div class="container">
        <div class="cards">
            <div class="card">
                <div class="val">{summary.get('total', 0)}</div>
                <div class="lbl">Total Tests</div>
            </div>
            <div class="card">
                <div class="val" style="color:#22c55e">{summary.get('passed', 0)}</div>
                <div class="lbl">Passed</div>
            </div>
            <div class="card">
                <div class="val" style="color:#ef4444">{summary.get('failed', 0)}</div>
                <div class="lbl">Failed</div>
            </div>
            <div class="card">
                <div class="val" style="color:{color}">{summary.get('pass_rate', 0)}%</div>
                <div class="lbl">Pass Rate</div>
            </div>
            <div class="card">
                <div class="val">{summary.get('avg_latency', 0)}ms</div>
                <div class="lbl">Avg Latency</div>
            </div>
        </div>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Method</th>
                    <th>URL</th>
                    <th>Status</th>
                    <th>Latency</th>
                    <th>Result</th>
                    <th>Assertions</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
    </div>
    <div class="footer">Generated by APIForge v0.1.0</div>
</body>
</html>"""
